'use client';
import {useEffect,useState} from 'react';
const empty={sku:'',name:'',slug:'',description:'',price:'',compare_at_price:'',cost_price:'',stock:'0',low_stock_threshold:'5',image:'',featured:false,new_arrival:false,movement:'',gender:'',case_material:'',case_diameter:'',dial_color:'',strap_material:'',water_resistance:'',warranty:'',brand_id:'',category_id:''};
export default function Products(){const [rows,setRows]=useState<any[]>([]),[brands,setBrands]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[edit,setEdit]=useState<string|null>(null),[msg,setMsg]=useState('');
async function load(){const r=await fetch('/api/admin/products');const d=await r.json();setRows(d.products||[]);setBrands(d.brands||[]);setCats(d.categories||[])} useEffect(()=>{load()},[]);
const change=(e:any)=>setForm({...form,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value});
async function save(e:any){e.preventDefault();setMsg('جاري الحفظ...');const payload={...form,price:Number(form.price),compare_at_price:form.compare_at_price?Number(form.compare_at_price):null,cost_price:form.cost_price?Number(form.cost_price):null,stock:Number(form.stock),low_stock_threshold:Number(form.low_stock_threshold)};const r=await fetch('/api/admin/products',{method:edit?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit?{id:edit,...payload}:payload)});const d=await r.json();if(!r.ok){setMsg(d.error||'فشل الحفظ');return}setMsg('تم الحفظ');setForm(empty);setEdit(null);load()}
function start(x:any){setEdit(x.id);setForm({...x,price:String(x.price),compare_at_price:x.compare_at_price==null?'':String(x.compare_at_price),cost_price:x.cost_price==null?'':String(x.cost_price),stock:String(x.stock),low_stock_threshold:String(x.low_stock_threshold)})}
async function del(id:string){if(!confirm('حذف المنتج؟'))return;const r=await fetch('/api/admin/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();setMsg(r.ok?'تم الحذف':d.error||'فشل الحذف');load()}
return <main className="admin"><small>CATALOG</small><h1>إدارة المنتجات</h1><div className="admin-two"><form className="panel admin-form" onSubmit={save}><h2>{edit?'تعديل المنتج':'إضافة منتج'}</h2>{[['sku','SKU'],['name','اسم المنتج'],['slug','Slug'],['price','السعر'],['compare_at_price','السعر قبل الخصم'],['cost_price','التكلفة'],['stock','المخزون'],['low_stock_threshold','حد التنبيه'],['image','رابط الصورة'],['movement','الحركة'],['gender','النوع'],['case_material','مادة الهيكل'],['case_diameter','قطر الهيكل'],['dial_color','لون المينا'],['strap_material','مادة السوار'],['water_resistance','مقاومة الماء'],['warranty','الضمان']].map(([n,l])=><label key={n}>{l}<input name={n} value={form[n]??''} onChange={change} required={['sku','name','slug','price','image'].includes(n)}/></label>)}<label>الوصف<textarea name="description" value={form.description||''} onChange={change}/></label><label>العلامة<select name="brand_id" value={form.brand_id||''} onChange={change} required><option value="">اختر</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>التصنيف<select name="category_id" value={form.category_id||''} onChange={change} required><option value="">اختر</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="checks"><label><input type="checkbox" name="featured" checked={!!form.featured} onChange={change}/> مميز</label><label><input type="checkbox" name="new_arrival" checked={!!form.new_arrival} onChange={change}/> جديد</label></div><button className="btn">{edit?'حفظ التعديل':'إضافة المنتج'}</button>{edit&&<button type="button" className="ghost" onClick={()=>{setEdit(null);setForm(empty)}}>إلغاء</button>}{msg&&<p className="note">{msg}</p>}</form><section className="panel"><h2>قائمة المنتجات ({rows.length})</h2><div className="table-wrap"><table className="admin-table"><thead><tr><th>المنتج</th><th>SKU</th><th>السعر</th><th>المخزون</th><th>الحالة</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.sku}</td><td>{Number(x.price).toLocaleString('ar-EG')} ج.م</td><td>{x.stock}</td><td>{x.stock<=x.low_stock_threshold?'منخفض':'متاح'}</td><td><button onClick={()=>start(x)}>تعديل</button><button className="danger-btn" onClick={()=>del(x.id)}>حذف</button></td></tr>)}</tbody></table></div></section></div></main>}
